### ISSUE TITLE
Atlas example gets stuck 

### ISSUE THREAD

**Issue by stevenjj** [junhyeokahn/PyPnC#2]
Not sure what I'm missing here but the Atlas example gets stuck after a few iterations.

I only know this because enabling the control computation time print out shows that it stops. This is not the case for the manipulator example.

````
Initialize
================================================================================
[WalkingState] STAND
ctrl computation time:  0.01023721694946289
ctrl computation time:  0.010233163833618164
ctrl computation time:  0.009650945663452148
ctrl computation time:  0.010210990905761719
ctrl computation time:  0.012571573257446289
ctrl computation time:  0.014132022857666016
ctrl computation time:  0.009562015533447266
ctrl computation time:  0.008954524993896484
ctrl computation time:  0.008904695510864258
ctrl computation time:  0.011704683303833008
ctrl computation time:  0.011358022689819336
ctrl computation time:  0.008925676345825195
ctrl computation time:  0.008788585662841797
ctrl computation time:  0.01023411750793457
ctrl computation time:  0.009508371353149414
ctrl computation time:  0.00990438461303711
ctrl computation time:  0.009284496307373047
ctrl computation time:  0.010796070098876953
ctrl computation time:  0.009235858917236328
ctrl computation time:  0.01134800910949707
ctrl computation time:  0.010422468185424805
````
Running on 20.04 LTS. Perhaps that's the issue.

**Comment by junhyeokahn** [comment]
I haven't tested the code with 20.04 but it shouldn't be matter in theory.
Maybe it should be stucked in the qp solvers I guess.
Could you show me the versions of dependencies?
You could do this with ```conda env export```

**Comment by stevenjj** [comment]
Ok. I'll make a VM for 18.04 and 20.04 later tonight and see if I can reproduce it.

**Comment by junhyeokahn** [comment]
I think it turns out to be related to the ```quadprog``` version.
I opened the issue [here](https://github.com/stephane-caron/qpsolvers/issues/47#issue-1049149011).
Temporarily, you could downgrade quadprog ```pip install quadprog==0.1.8``` and it will resolve the issue

**Comment by junhyeokahn** [comment]
This is resolved by upgrading ```qpsolvers``` version! Check [this](https://github.com/stephane-caron/qpsolvers/issues/47#issue-1049149011) and [this](https://github.com/junhyeokahn/PyPnC/commit/aa450b8ff33366b01c863ccf5edf2bea01702b85#diff-92c8faf707fdee228d2b3ddcbb5165ce089f32caecc30ec371964d69d5a45bf6R21) out for further detail.
